package org.netrajyoti.routing;
public enum Concern { SUDDEN_VISION_CHANGE, SEVERE_PAIN, INJURY_OR_CHEMICAL, REDNESS_OR_DISCHARGE, BLURRY_VISION, READING_OR_DISTANCE_DIFFICULTY, EYE_CHECK_OR_GLASSES, OTHER }
